### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: io/vertx/micrometer/impl/Label

### ISSUE THREAD

**Issue by pankajtaneja86** [vert-x3/vertx-micrometer-metrics#102]
Have these entries in my POM.xml

    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-micrometer-metrics</artifactId>
      <version>3.8.3</version>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-influx</artifactId>
      <version>1.3.5</version>
    </dependency>

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: io/vertx/micrometer/impl/Label
        at com.ABC.commerce.payments.instruments.VerticleTest.before(VerticleTest.java:97)
Caused by: java.lang.NoClassDefFoundError: io/vertx/micrometer/impl/Label

<img width="730" alt="Screen Shot 2020-03-16 at 3 59 53 PM" src="https://user-images.githubusercontent.com/17147884/76806657-4434e680-679f-11ea-9478-738d5ff8a306.png">
<img width="743" alt="Screen Shot 2020-03-16 at 4 00 08 PM" src="https://user-images.githubusercontent.com/17147884/76806664-472fd700-679f-11ea-8a3f-46009122e913.png">

**Comment by jonatan-ivanov** [comment]
Hi,

There is no `io.vertx.micrometer.impl.Label` (singular) class anymore, it was moved/renamed to `io.vertx.micrometer.Label` (no `impl`) in the package name. https://github.com/vert-x3/vertx-micrometer-metrics/blob/master/src/main/java/io/vertx/micrometer/Label.java

Your code depends on an older version of vert.x maybe 3.5.x, update the package name ant it will be ok.

**Comment by pankajtaneja86** [comment]
Thank you @jonatan-ivanov
