### ISSUE TITLE
Client metrics implementation

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-micrometer-metrics#106]
This https://github.com/eclipse-vertx/vert.x/issues/3467 provides a client metrics SPI (similar to HTTP client metrics) that will be used by Vert.x clients to report metrics, e.g the SQL client uses it since https://github.com/eclipse-vertx/vertx-sql-client/issues/698

**Comment by vietj** [comment]
@jotak FYI , this should not be too much work

**Comment by jotak** [comment]
What's the expectations for these metrics? I guess counter + processing time measurement for both requests and responses?
Is there an implementation reference (dropwizard...) or not yet?

**Comment by jotak** [comment]
Put differently, what is worth measuring ? Given the example provided, I would say:

- Queue time
- Full processing time w/ network latency (from RQ begin to RS end)

Does RQ processing time alone, or RS time alone make sense to measure? (btw I'm seeing in https://github.com/eclipse-vertx/vertx-sql-client/commit/e8b9e0437d0ae30978d03d203d3f0d90feb45600 that RQ begin is called without RQ end)

**Comment by vietj** [comment]
is there a bug in SQL client implementation ?

**Comment by vietj** [comment]
@jotak see https://github.com/eclipse-vertx/vertx-sql-client/commit/0ff45b2f21ed61c657a1ab20d3c4ff9a04fb7b29 thanks :-)
