### ISSUE TITLE
VertxMetricsImpl.createClientMetrics is not thread-safe (ConcurrentModificationException)

### ISSUE THREAD

**Issue by ylemoigne** [vert-x3/vertx-micrometer-metrics#118]
Reposting from : https://github.com/eclipse-vertx/vertx-sql-client/issues/786

### Version

4.0.0-SNAPSHOT

### Context

The exception :
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1226)
	at io.vertx.micrometer.impl.VertxMetricsImpl.createClientMetrics(VertxMetricsImpl.java:150)
	at io.vertx.mysqlclient.impl.MySQLPoolImpl.create(MySQLPoolImpl.java:33)
	at io.vertx.mysqlclient.MySQLPool.pool(MySQLPool.java:82)

Appear randomly but quite often (1 launch on 3 or 4 maybe).
The pool is created outside vertx event loop thread (on a thread coming from kotlin Dispatchers.Default)
On the same vertx instance, it is possible that another pool with the same configuration is created by another thread also coming from kotlin Dispatchers.Default.

### Do you have a reproducer?

No.

### Extra

I did not have this issue with vertx 3.9.3, so I suspect this is a bug but I'm perfectly ok if the answer is that the pool creations must be single threaded (from event loop or not).

**Comment by jotak** [comment]
Thanks for reporting @ylemoigne 
I just pushed a fix. Better to enforce thread-safety, I think, than an implicit restriction to use the event loop in this scenario. (Though I'm not sure if there can be other side-effects in other places ...)

BTW only 4.0.0 is affected as there was no sql client metrics in 3.x

**Comment by jotak** [comment]
Closing, was fixed in 4.0.0 snapshot & release candidates
https://github.com/vert-x3/vertx-micrometer-metrics/commit/849b78927a38345927f67685669315ffb177e8f9
