### ISSUE TITLE
Why the verticle metrics 'vertx_verticle_deployed' was deleted?

### ISSUE THREAD

**Issue by liukch** [vert-x3/vertx-micrometer-metrics#120]
I am upgrading Vertx from 3.9.5 to 4.0.0, I found the verticle metrics 'vertx_verticle_deployed' was deleted.
And the [vertx-4-migration-guide](https://vert-x3.github.io/vertx-4-migration-guide/index.html#changes-in-micrometer-metrics_changes-in-common-components) not mention of this change at all.
I am very confused with this improvement.
Isn't monitoring verticle number  essential for all Vertx projects?
Or else there is a new way to catch this metrics?

This is the metrics doc in 3.9.5 
https://vertx.io/docs/3.9.5/vertx-micrometer-metrics/java/#_verticle_metrics

**Comment by vietj** [comment]
it was removed because we felt it was not really used.

please open an issue to make your case and we can discuss from there.

**Comment by liukch** [comment]
I use Promotheus to catch metrics and Grafana to compose observability dashboards.
The ```vertx_verticle_deployed``` is always an important panel to tell me the accurate verticle number of all this service instance.
If do not have this, I need calculate number by myself.

**Comment by vietj** [comment]
if that's a blocker for you, please open an issue for it

**Comment by liukch** [comment]
OK I will open a new issue.
