### ISSUE TITLE
The 'vertx_verticle_deployed' verticle metrics was deleted in 4.0.0

### ISSUE THREAD

**Issue by liukch** [vert-x3/vertx-micrometer-metrics#121]
I upgrade Vertx version from 3.9.5 to 4.0.0, I find this metric was deleted:
1. The [vertx-4-migration-guide](https://vert-x3.github.io/vertx-4-migration-guide/index.html#changes-in-micrometer-metrics_changes-in-common-components) not mention of this change at all, this makes me confused during the upgrade process, I have to check the source code and Vertx documents to confirm  this change.
2. It is a blocker for me, because I check this monitoring metric very frequently, I need to know how many total verticles in all of my service instance.

**Comment by liukch** [comment]
#120

**Comment by vietj** [comment]
cc @jotak

**Comment by vietj** [comment]
we removed it because we thought it was not very useful

**Comment by liukch** [comment]
If we do not have this, how should I know the total verticle number?
My be I will add a customized metric which have a same effect with 'vertx_verticle_deployed' or calculate it by my myself.

**Comment by vietj** [comment]
@liukch you can cast use `Vertx.deploymentIDs()` and then retrieve each deployment using `VertxInternal` where you can count the number of instances of `Deployment`.

**Comment by jotak** [comment]
I did not realize that it was a 4.0 change, as it was pretty old, I though it was also in 3.9 branch.... sorry about that :-/

If I'm correct the removal was targeting the whole SPI, not just this implementation, so if we want to take it back we need to change vertx-core too, and dropwizard.

**Comment by vietj** [comment]
yes, it might be easier and more convenient to expose this as an API in
Vert.x I think than as a metric

**Comment by liukch** [comment]
OK, thank a lot.
