### ISSUE TITLE
NPE in VertxEventBusMetrics.endHandleMessage

### ISSUE THREAD

**Issue by nistorbog** [vert-x3/vertx-micrometer-metrics#127]
java.lang.NullPointerException#	at io.vertx.micrometer.impl.VertxEventBusMetrics.endHandleMessage(VertxEventBusMetrics.java:99)#	at io.vertx.micrometer.impl.VertxEventBusMetrics.endHandleMessage(VertxEventBusMetrics.java:33)#	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:273)#	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:249)#	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:573)#	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:532)#	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)#	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35)#	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)#	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)#	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)#	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)#	at java.lang.Thread.run(Thread.java:748)#

**Comment by jotak** [comment]
Hi @nistorbog ,
Which version of vert.x is it, and can you consider upgrading?
(a similar issue was fixed a while ago and looking at your stack trace, I think it's the same cause : https://github.com/vert-x3/vertx-micrometer-metrics/pull/82 )
