### ISSUE TITLE
[UnixSocketTest]Test Failed on power architecture (ppc64le) 

### ISSUE THREAD

**Issue by vikasgupta8** [vert-x3/vertx-micrometer-metrics#130]
### Questions

I am porting vertx-micrometer-metrics package on power architecture (ppc64le). The build is successful but one testcase (UnixSocketTest) is failing due to timeout.
I have build and tested on Linux x86_64 Architecture also and the build and test was successful.

I have debugged the source code and found it is failing in function DomainSocketServer() to create Http Server (on ppc64le). 
As I am trying this build on "rhel UBI 8.4" docker container.

Just to verify and debug, I have put some logs into code snippet to verify the scenario below.

public class DomainSocketServer extends AbstractVerticle {
    @Override
    public void start(Promise<Void> startPromise) {
      vertx.createHttpServer().requestHandler(req -> {})
        .listen(SocketAddress.domainSocketAddress("/var/tmp/myservice.sock"), ar -> {
          if (ar.succeeded()) {
            **System.out.println("VIKAS:DomainSocketServer SUCCESS");**
            startPromise.complete();
          } else {
            **System.out.println("VIKAS:DomainSocketServer FAILURE");**
            startPromise.fail(ar.cause());
          }
        });
    }
I am getting failure log here.

### Version

master

### Context

I encountered an exception which looks suspicious while porting vertex-micrometer-metrics on power architecture (ppc64le).

### Do you have a reproducer?
No

### Steps to reproduce

1. Clone the repo on power architecture (ppc64le) 
2. Resolve all dependencies.
3. Build and test with below command.
    **mvn clean install**
4. UnixSocketTest fails with timeout error.

### Extra

[root@4d6e7cf404ea vertx-micrometer-metrics]# uname -a
Linux 4d6e7cf404ea 4.18.0-305.10.2.el8_4.ppc64le #1 SMP Tue Jul 20 17:27:00 UTC 2021 ppc64le ppc64le ppc64le GNU/Linux

[root@4d6e7cf404ea vertx-micrometer-metrics]# java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
[root@4d6e7cf404ea vertx-micrometer-metrics]#

Could you please help to provide some pointers to debug further.

**Comment by tsegismont** [comment]
Can you paste the stacktrace?

**Comment by vikasgupta8** [comment]
Hi Thomas,

Below are the stack trace. 
And the log starting with VIKAS in **bold** are my added logs.

Running io.vertx.micrometer.UnixSocketTest
**VIKAS:DomainSocketServer FAILURE
VIKAS:DomainSocketClientTriggerVerticle FAILURE**
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.607 sec <<< FAILURE! - in io.vertx.micrometer.UnixSocketTest
shouldWriteOnUnixSocket(io.vertx.micrometer.UnixSocketTest)  Time elapsed: 10.606 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out
        at io.vertx.ext.unit.impl.CompletionImpl.awaitSuccess(CompletionImpl.java:99)
        at io.vertx.micrometer.RegistryInspector.waitForValue(RegistryInspector.java:114)
        at io.vertx.micrometer.UnixSocketTest.shouldWriteOnUnixSocket(UnixSocketTest.java:51)


Results :

Tests in error:
  UnixSocketTest.shouldWriteOnUnixSocket:51 » Timeout Timed out

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.123 s
[INFO] Finished at: 2021-11-30T04:38:40Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project vertx-micrometer-metrics: There are test failures.
[ERROR]
[ERROR] Please refer to /home/tester/vertx-micrometer-metrics/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[root@4d6e7cf404ea vertx-micrometer-metrics]#

**Comment by vietj** [comment]
which OS are you using ?

**Comment by vikasgupta8** [comment]
Hi Julien,

I am using RHEL 8.5. Please find more details below.

[root@4d6e7cf404ea vertx-micrometer-metrics]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.5"
[root@4d6e7cf404ea vertx-micrometer-metrics]#

**Comment by vietj** [comment]
you need to change this jar

   <dependency>
      
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-epoll</artifactId>
      <classifier>linux-x86_64</classifier>
      <scope>test</scope>
    </dependency>

to use the PPC one if that exist or recompile it for PPC using the sources

**Comment by vikasgupta8** [comment]
Thank you Julien for guiding to right direction. 

I have build the **netty-transport-native-epoll** for **ppc64le** and added dependency into pom.xml file for vertx-micrometer-metrics.

Now the test is passing.

Thank you very much for your help.
