### ISSUE TITLE
Implement custom tags provider for HTTP Client metrics

### ISSUE THREAD

**Issue by jordillachmrf** [vert-x3/vertx-micrometer-metrics#133]
#### Describe the feature

Implement custom tags provider for HTTP Client metrics, as already done for http server metrics
 https://github.com/vert-x3/vertx-micrometer-metrics/pull/124

#### Use cases

Expose extra tags such as path and remoteHost for http client metric

I could allocate some time to create the PR if the team thinks is useful. 

Should we use the same RequestTagProvider ? or create a dedicated one for http client
 https://github.com/vert-x3/vertx-micrometer-metrics/blob/master/src/main/java/io/vertx/micrometer/impl/VertxMetricsImpl.java#L94

**Comment by jotak** [comment]
Hey @jordillachmrf , I think it makes sense to have the same for client metrics. Thanks for offering your help!

> Should we use the same RequestTagProvider ? or create a dedicated one for http client
I would say it's better to create a dedicated setting for client requests

**Comment by tsegismont** [comment]
Fixes in #134
