### ISSUE TITLE
PrometheusScrapingHandler is not working with CompositeMeterRegistry

### ISSUE THREAD

**Issue by SaschaLucius** [vert-x3/vertx-micrometer-metrics#137]
### Version

4.2.5

### Context

I encountered an error while using a `CompositeMeterRegistry` with the `PrometheusScrapingHandler`.
I would expect that this should work as long as a `PrometheusMeterRegistry` is registered somewhere.

### Do you have a reproducer?

No

### Steps to reproduce

1. start with following example https://vertx.io/docs/vertx-micrometer-metrics/java/#_binding_metrics_to_an_existing_vert_x_web_router
2. create a `CompositeMeterRegistry`
3. register a `PrometheusMeterRegistry` in it
4. set the `CompositeMeterRegistry` with `setMicrometerRegistry` in the `MicrometerMetricsOptions`
5. access the registered endpoint and see ""

### Extra
Resources which helped me to workaround the issue:
- https://paulswithers.github.io/blog/2020/04/18/micrometer-composite-registries
- have written my own `PrometheusScrapingHandlerImpl` based on this blog article
- https://github.com/vert-x3/vertx-micrometer-metrics/blob/master/src/main/java/io/vertx/micrometer/impl/PrometheusScrapingHandlerImpl.java

```
        if (registry instanceof CompositeMeterRegistry) {
            Optional<MeterRegistry> prometheusMeterRegistry = ((CompositeMeterRegistry) registry).getRegistries()
                    .stream()
                    .filter(PrometheusMeterRegistry.class::isInstance)
                    .findAny();
            if (prometheusMeterRegistry.isPresent()) {
                registry = prometheusMeterRegistry.get();
            }
        }
```

**Comment by tsegismont** [comment]
Thanks for reporting this.

This will be fixed in #157 : you will be able to provide a specific Prometheus meter registry when creating the scraping handler.
