### ISSUE TITLE
Incorrect Gauge id mapping scope

### ISSUE THREAD

**Issue by jhalliday** [vert-x3/vertx-micrometer-metrics#139]
### Version

4.2.6

### Context

Whilst developing a partial fix for #91 I've realised the current approach is not just somewhat slow, it also appears to be incorrect in certain circumstances.

Gauges instances each contain an Id->T map, whilst MeterRegistry instances have an Id->Gauge(T) map. This becomes a problem when multiple Gauges instances have a shared MeterRegistry instance, since despite the locking you'll get cases where Gauge.builder.register will see a pre-existing mapping that the Gauges instance calling it doesn't know about because it's in the map of some other Gauges instance. In such cases, a new T is put into the Gauges.gauges map whilst the underlying Gauge continues to use a pre-existing one. Thus metrics don't update correctly.

This seems to be a problem only when multiple vertx instances share a registry name, since BackendRegistries will then give them the same instance. It's arguably incorrect usage to attempt that, though nothing prevents it.

This is also a problem in the test suite, which puts multiple vertx instance on the same metrics registry. Options seem to be: make the cleanup between tests a blocking operation so tests are no longer potentially concurrent and make it clear existing metrics from the registry before it's reused by the next test; or change registryName use so each test setup gets a unique one (right now it's unique per test class, not per test function).

**Comment by tsegismont** [comment]
@jhalliday in #146 we make sure all tests use a different registry.

Users creating multiple Vert.x instances inside a same JVM are often not using the metrics SPI but rather build their own metrics.
If they are, they should set a registry name or force a registry instance.

Thanks for this report, it was helpful.
