### ISSUE TITLE
Expose new InfluxDb 2.0 configuration options so Vert.x can support influxDb 2.0 connections

### ISSUE THREAD

**Issue by redkite58** [vert-x3/vertx-micrometer-metrics#141]
Seen in Vext.x version 4.3.1

The Vert.x Micrometer Metrics 4.3.1 release has now included the io.micrometer-> micrometer-registry-influx 1.8.4 as a compiled dependency. This dependency provides support for InfluxDb 2.0 connections (see https://github.com/micrometer-metrics/micrometer/issues/1974 for more details). 

InfluxDb 2.0 provides three new connection properties:
- org 
- bucket
- token
- 
If these new configuration options are set then the InfluxDb 1.8.4 library will create InfluxDb 2.0 connections, if the old 'db' property is used the library will fall back to InfluxDb 1.0 connections.  

The **vertx.micrometer.VertxInfluxDbOptions** class needs to be updated to support these new configuration operations. This should then enable Vert.x to support InfluxDb 2.0 connections.

**Comment by tsegismont** [comment]
@vietj I have asked @redkite58 to file this issue in https://groups.google.com/g/vertx/c/9mCsl4rKhhc/m/rIS_xANBBgAJ

@redkite58 you should start by adding the new properties to `InfluxDBOptions` and update its `toMicrometerConfig`.

**Comment by tsegismont** [comment]
@redkite58 still want to contribute this?
