### ISSUE TITLE
about micrometer

### ISSUE THREAD

**Issue by HelloTo4x** [vert-x3/vertx-micrometer-metrics#142]
Hi, i am reading your project, why do you use Micrometer for collecting metric ? why don't you use Grafana + Prometheus to collect log and metric ? Do you know about pros and cons of Micrometer, can you tell me about it

**Comment by tsegismont** [comment]
Micrometer is a metrics facade. We use it because backends are pluggable (Prometheus, Influx, JMX, ... etc).

You can definitely have a setup where Vert.x stores metrics in Prometheus and then visualize them in Grafana.
See https://how-to.vertx.io/metrics-prometheus-grafana-howto/
