### ISSUE TITLE
Using Micrometer Filters to disable any VertX Gauge measurement causes infinite loop

### ISSUE THREAD

**Issue by DemonicTutor** [vert-x3/vertx-micrometer-metrics#150]
### Version

VertX 4.3.2

### Context

(https://github.com/vert-x3/vertx-micrometer-metrics/commit/5a4a10a16695b8d81866d0325e9125bc63e8d43d)

In our microservices we are filtering out certain metrics from micrometer / prometheus to reduce the overall load (we dont need them) and this also includes specific metrics tracked by vertx like:

```
"vertx.pool.ratio"
"vertx.pool.completed"
"vertx.eventbus.handlers"
```

for now i fixed this for us by changing from using Micrometer Filter's to disable the metrics to whitelisting the metrics to be scraped instead but it would be nice if the `NullGauge` from Micrometer would be supported.

```
final var whitelist = pmr.getMeters().stream()
              .map(Meter::getId)
              .filter(id -> !filteredMetrics.contains(id.getName()))
              .map(id -> id.getConventionName(NAMING_CONVENTION))
              .collect(Collectors.toUnmodifiableSet());
            System.err.println(whitelist);
            return ((PrometheusMeterRegistry) pmr).scrape(TextFormat.CONTENT_TYPE_004, whitelist);
```

### Do you have a reproducer?

no - can provide one on demand

### Steps to reproduce

```
final var reg = BackendRegistries.getDefaultNow();
 reg.config().meterFilter(MeterFilter.deny(id -> "vertx.eventbus.handlers" == id.getName())); // we check for a whole configurable list here
// filters do not retroactively remove metrics which have been collected already - has to be done afterwards manually once
reg.forEachMeter(meter -> {
  if ("vertx.eventbus.handlers" == id.getName())) {
    reg.remove(meter.getId());
  }
});
```

### Extra

openJdk 18

**Comment by tsegismont** [comment]
Thanks for the report @DemonicTutor
