### ISSUE TITLE
Allow to report to any number of backends

### ISSUE THREAD

**Issue by jotak** [vert-x3/vertx-micrometer-metrics#16]

**Comment by checketts** [comment]
I haven't dug into the vert.x code to see the current implementation, but I'm curious why the current Micrometer doesn't automatically allow all the backends Micrometer already supports.

For example Micrometer provides a `CompositeRegistry` that should address this issue already.

**Comment by jotak** [comment]
@checketts this is because in Vert.x metrics SPI is activated through using dedicated option object for configuration, the user doesn't initialize the micrometer registry(ies) himself. That option class ( https://github.com/vert-x3/vertx-micrometer-metrics/blob/master/src/main/java/io/vertx/micrometer/VertxPrometheusOptions.java ) is currently not adapted for multiple backends.
It's really not a big deal to do it.

**Comment by jotak** [comment]
This is partly fixed in https://github.com/vert-x3/vertx-micrometer-metrics/pull/24 , although we can keep this ticket opened if we want better integration with metrics options

**Comment by tsegismont** [comment]
@jotak for this one I think `io.vertx.micrometer.backends.BackendRegistries#setupBackend` could be changed to create a composite registry if more than one backend options are present and enabled.

**Comment by jotak** [comment]
multiple backends now possible and documented
