### ISSUE TITLE
Add support for Micrometer's new Observation API

### ISSUE THREAD

**Issue by jonatan-ivanov** [vert-x3/vertx-micrometer-metrics#162]
#### Describe the feature

With [Micrometer](https://micrometer.io/) 1.10.0 (I'm a maintainer), a new API was released called the [Observation API](https://micrometer.io/docs/observation). It lets users instrument their components once and then get multiple benefits out of it e.g.: metrics, distributed tracing, (audit) logs, publishing arbitrary events, etc.

(We also released [Micrometer Tracing](https://github.com/micrometer-metrics/tracing) (it's a new project) which is not a must but plays nicely with the Observation API and it can bridge calls to OpenTelemetry or OpenZipkin's Brave).)

#### Use cases

The use cases are quite wild, the goal of the Observation API is to be able to cover a lot of the Observability needs of the users, for example:
- Users want metrics in their apps (they can use micrometer metrics or other libraries, e.g.: dropwizard-metrics)
- Users want distributed tracing in their apps (they can use Micrometer Tracing with Brave/OTel or other libraries)
- Users want both metrics and distributed tracing in their apps
- Users want to listen to and publish custom events in their applications and emit logs, write an audit DB, etc.

#### Contribution

Since Vert.x needs to be instrumented this should be implemented in the Vert.x codebase.
The implementation should be similar to the current usage of Micrometer `Timer` but instead of starting/stopping a `Timer`, we need to start/stop an `Observation`. See migration guide here: https://github.com/micrometer-metrics/micrometer/wiki/Migrating-to-new-1.10.0-Observation-API

**Comment by tsegismont** [comment]
Thank you for the heads-up @jonatan-ivanov , this should be considered when implementing #164

**Comment by brunobat** [comment]
cc @cescoffier @jponge

**Comment by brunobat** [comment]
Created this: https://github.com/micrometer-metrics/micrometer/issues/3829

**Comment by jonatan-ivanov** [comment]
Hi @tsegismont,
Could you please add some explanation for closing the issue?

**Comment by tsegismont** [comment]
Hi @jonatan-ivanov 

I've read through the new Observation API document as well as the migration guide. As I understand it, the new API does not make `Timer`/`Sample` irrelevant, but introduces new models in order to be able to support both metrics and tracing. But Vert.x already has a tracing SPI with different implementions (OTel, OpenTracing, Zikpkin). So, unless `Timer`/`Sample` API is going away in a future version, the Observation API is not useful to us at this moment.

**Comment by jonatan-ivanov** [comment]
Hi,

The Observation API's scope is broader than supporting metrics and tracing. Indeed, we provide components (handlers) for metrics and tracing out of the box but you can do a lot more, that I tried to show in the description above:
>Users want to listen to and publish custom events in their applications and emit logs, write an audit DB, etc.

Basically anything that happens in your app, you can get notified about it and decide what you can do with the data. On top of the above users seem to be quite creative about it: emit custom log events, integrate with async-profiler, generate technical documentation (capturing data during tests), customized visualization of the call-tree, generate sequence diagrams for calls (capturing data during tests).

On top of this, you can consolidate your observability components and SPIs.

There is one more advantages of using the Observability API on top of `Timer` or the OTel SDK: the Observation API lets you define your own convention to name things. So if you want to use your own namings right now but later on want to migrate to OTel's semantic conventions (once they stabilize), you can do this without breaking things. Users can define their own naming conventions too. Also, because of these components, users can generate documentation about the data (metrics and spans and their tags) available through instrumentation.

**Comment by jonatan-ivanov** [comment]
@tsegismont What do you think? ^

**Comment by jonatan-ivanov** [comment]
@tsegismont Ping? :)

**Comment by tsegismont** [comment]
Hi @jonatan-ivanov 

Can you show me an example of what users could do if we replaced the few timers we have with the observation API equivalent?

**Comment by jonatan-ivanov** [comment]
The most apparent one is they will get distributed tracing support too with the same instrumentation: you need to instrument it only once.

Other than that they can do:
- logging
- saving events to an audit table
- generate documentation automatically
- sending events to various observability backends
- detecting anomalies
- one of our users is using async-profiler with the Observation API
- one of our users is generating sequence diagrams by running tests against instrumented components

The big advantage is that they can use the data and process it however they want, they are not constrained to one use-case (i.e.: metrics or tracing).

**Comment by jonatan-ivanov** [comment]
@tsegismont What do you think about the above?

**Comment by jonatan-ivanov** [comment]
@tsegismont Ping? :)

**Comment by tsegismont** [comment]
@jonatan-ivanov I'm not convinced we can replace our tracing spi with the 3 timers we have in this module.

**Comment by jonatan-ivanov** [comment]
I think you misunderstood what I said above. This is about using the Observation API for tracing and metrics needs, not about replacing the tracing instrumentation with Timers (that does not make any sense to me too).

Also, I might learned recently that this issue might be in the wrong repo. Do you have any kind of instrumentation for vert.x 4?
