### ISSUE TITLE
Upgrade to Micrometer 1.10

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-micrometer-metrics#164]
We had to [revert](https://github.com/vert-x3/vertx-micrometer-metrics/commit/d4d4fb6877c8a02582ecfbc568ff6e8e9adc2fc2) the upgrade to `1.10` in Vert.x `4.3.5` because it creates a [conflict](https://github.com/vert-x3/vertx-lang-kotlin/actions/runs/3485327605/jobs/5830763975#step:4:247) with our supported version of Kotlin.

We need to make the upgrade again in 4.4, and that means probably some upgrades in `vertx-kotlin` too.

**Comment by yeikel** [comment]
We can target `1.10.3` as that's the latest version at the moment
