### ISSUE TITLE
Missing metrics when using `setServerRequestTagsProvider` with a different set of tags for different requests

### ISSUE THREAD

**Issue by mervyn-mccreight** [vert-x3/vertx-micrometer-metrics#173]
### Version

* 4.3.3
* 4.4.0

### Context

When using one `Vertx` instance with metrics included to host a http-server with `Kotlin` and `Coroutines` and a `ServerRequestTagsProvider` that returns different Tags (key + value is different) for different type of requests, metrics are missing.

### Do you have a reproducer?

* https://github.com/mervyn-mccreight/vertx-metrics-bug

### Steps to reproduce

Just execute the `AppTest.catchMetrics` test and you can see the output of the metrics.
I'd expect metrics for all `GET` and `POST` requests, but the `POST` request metrics are missing.
If you change the `ServerRequestTagsProvider` to e.g. return a Tag with the same key, but different values for different requests, the metrics are there. The same goes when you completely remove the `ServerRequestTagsProvider`.

### Extra

* OS: MacOS, but the same happens on a linux machine
* JVM version: Tested with 17 and 19. Was able to reproduce the same behaviour with both versions.

**Comment by tsegismont** [comment]
Thank you

Le ven. 10 mars 2023, 20:04, Mervyn McCreight ***@***.***> a
écrit :

**Comment by mervyn-mccreight** [comment]
There may be a connection to https://github.com/micrometer-metrics/micrometer/issues/3508
I'll try to investigate further and find out if this is really depending on vert.x or if it is an issue with micrometer-metrics.
I don't know if that is intended behaviour though, but I wouldn't know why it should be.

**Comment by mervyn-mccreight** [comment]
Seeing https://github.com/micrometer-metrics/micrometer/issues/877 I'm pretty sure it is a problem with the micrometer implementation.

**Comment by tsegismont** [comment]
Right, thanks for the update. Let's keep the issue open until the upstream issue comes to a resolution.

**Comment by tsegismont** [comment]
Closing as there's nothing we can do. Workaround in this comment: https://github.com/micrometer-metrics/micrometer/issues/877#issuecomment-944894069

**Comment by mervyn-mccreight** [comment]
@tsegismont is it okay from your side when I delete the reproducer repository then? :)
