### ISSUE TITLE
How to metrics eventBus processing time?

### ISSUE THREAD

**Issue by eahau** [vert-x3/vertx-micrometer-metrics#179]
As described in the document [Event Bus Metrics](https://vertx.io/docs/vertx-micrometer-metrics/java/#_event_bus)
There are available metrics, like: `summary` `gauge` and `count`, But I want to know how to metrics eventBus processing time?
Example: `Service A` send message to `Service B`, `Service B` received message, the total time consumed.

**Comment by tsegismont** [comment]
Do you mean how to measure total time from sending message to receiving response in A?

Then you could use a timer: Then you could use a Micrometer timer: https://micrometer.io/docs/concepts#_storing_start_state_in_timer_sample

**Comment by eahau** [comment]
> Do you mean how to measure total time from sending message to receiving response in A?
> 
> Then you could use a timer: Then you could use a Micrometer timer: https://micrometer.io/docs/concepts#_storing_start_state_in_timer_sample

Thx,  I'll try this.

**Comment by eahau** [comment]
> Do you mean how to measure total time from sending message to receiving response in A?
> 
> Then you could use a timer: Then you could use a Micrometer timer: https://micrometer.io/docs/concepts#_storing_start_state_in_timer_sample

Maybe what I describe is not clear enough. This is an async message send. I don't care about the time consumption of the sender of the message. What I care about is the time consumption of a message from sending to receiving.

**Comment by tsegismont** [comment]
Perhaps can you illustrate your question with a snippet?

**Comment by eahau** [comment]
> Perhaps can you illustrate your question with a snippet?


Like this: NodeA send message to NodeB
```java
 //*************** NodeA ***************//
    final String address = "address";
    final EventBus clusterEventBus = vertx.eventBus();
    // send message to other node
    clusterEventBus.send(
        address,
        "message",
        new DeliveryOptions().addHeader("start", String.valueOf(System.nanoTime()))
    );

//*************** NodeB ***************//
final StatsDClient statsDClient = new NoOpStatsDClient();
clusterEventBus.consumer(address, message -> {
  final long elapsed = System.nanoTime() - Long.parseLong(message.headers().get("start"));
  // report the time consumption of a message from sending to receiving
  statsDClient.time(address + ".received", elapsed);
});
```
But this isn't accurate, because this message may be delayed in the task queue for a while.
see [private Queue<Message<T>> pending = new ArrayDeque<>(8);](https://github.com/eclipse-vertx/vert.x/blob/ec769595b9f40b1d9368e95be7e164d22c628fdf/src/main/java/io/vertx/core/eventbus/impl/MessageConsumerImpl.java#L47)

**Comment by tsegismont** [comment]
Thanks for the update
