### ISSUE TITLE
Push metrics to prometheus pushgateway

### ISSUE THREAD

**Issue by curtiseng** [vert-x3/vertx-micrometer-metrics#221]
#### Describe the feature

Push metrics to prometheus pushgateway.

#### Use cases

We want collect metrics by vector, but there's no K8S discovery in prometheus scrape source. So we need use push architecture, push is a more flexible.

#### Contribution

Maybe this is a common feature, if not, is there any suggest.

**Comment by tsegismont** [comment]
There is no built-in support for push gateway in the Micrometer Metrics registry. You can use this [workaround](https://github.com/micrometer-metrics/micrometer/issues/3661#issue-1593758081) to send data to the pushgateway.
