### ISSUE TITLE
Micrometer configuration lifecycle violation

### ISSUE THREAD

**Issue by jonatan-ivanov** [vert-x3/vertx-micrometer-metrics#224]
Micrometer's `MeterRegistry` should be "configured" (see `MeterRegistry.Config`) before registering `Meter` instances to it. For example `MeterFilter`s should be configured before a `Meter` has been registered to the registry.

Historically, Micrometer has allowed configuring `MeterFilter`s after meters have been registered but due to certain performance optimizations with https://github.com/micrometer-metrics/micrometer/pull/4917 we took a step toward warning users about this situation.

See:
- https://github.com/micrometer-metrics/micrometer/issues/4920
- https://github.com/micrometer-metrics/micrometer/pull/4917

It seems in certain cases Vert.x configures a `MeterFilter` after a `Meter` has been registered to the registry causing the warning mentioned above. See https://github.com/micrometer-metrics/micrometer/issues/4920#issuecomment-2125854418 by @sanyarnd with a reproducer.

@sanyarnd could you please provide the Vert.x version you are using and any additional details you have?

**Comment by tsegismont** [comment]
I'll look into it

**Comment by tsegismont** [comment]
I read the logs in the comment posted by  @sanyarnd  in https://github.com/micrometer-metrics/micrometer/issues/4920

The warning is logged when the Vert.x Metrics instance is created. No meter is registered by Vert.x at this stage. Users must either:

- delay meters registration until Vert.x has set up its Metrics instance, or
- enable all labels (`MicrometerMetricsOptions#setLabels`) and configure no matcher (with `MicrometerMetricsOptions addLabelMatch`)

Feel free to reach out if more info is needed

**Comment by jonatan-ivanov** [comment]
@tsegismont Is there a way to guide the users towards how to register heir own `Meter`s at startup? E.g.: a section in the docs?

**Comment by tsegismont** [comment]
@jonatan-ivanov I don't believe we should document how to register their own meters, the Micrometer doc is does it well. But thanks for mentioning docs, I think it would be nice to have a note that explains that Vert.x can register meter filters and, for this reason,  they can see Micrometer's warning in the logs.

**Comment by tsegismont** [comment]
Closed by caca2d7f4df854821005e1667d9adf7415d54e7f
