### ISSUE TITLE
 Micrometer not working with Clustered Vertx

### ISSUE THREAD

**Issue by gklsan** [vert-x3/vertx-micrometer-metrics#30]
Hi i try to use  Micrometer in my project with clustered vertx. Is it any way to overcome this?.

**Comment by gklsan** [comment]
Hi @vietj,  I'm using JRuby in my application with the Jubilee gem. I try to configure the micrometer in vertx option with clusteredVertx. If I enable setMetricsOptions true my application not starting. [Here](https://github.com/Mahaswami/jubilee/blob/5556997846fcce3da4cfa11be699e677acb5259d/src/main/java/org/jruby/jubilee/RubyPlatformManager.java#L63) is the file where I try the following configuration:
` MicrometerMetricsOptions opts = new MicrometerMetricsOptions().setInfluxDbOptions(
               new  @VertxInfluxDbOptions().setEnabled(true)).setEnabled(true);
vertxOptions.setMetricsOptions(opts);
`

**Comment by vietj** [comment]
do you have micrometer metrics in your classpath ? 

alternatively you can try setup the `factory` on `MetricsOptions` directly `io.vertx.micrometer.impl.VertxMetricsFactoryImpl`

**Comment by gokulmss** [comment]
@vietj kindly check this repository(https://github.com/gokulmss/clustered-vertx-with-mircometer) to reproducing this issue. This is the isolated code for the clear understand. To run refer README.md.

**Comment by tsegismont** [comment]
The only problem I can see in the reproducer is that you deploy verticles just after invoking `Vertx.clusteredVertx()`. This doesn't work (hence the NPE) but it is expected: creating a clustered Vert.x is an async operation so you can only deploy verticle when the Vert.x instance is ready. Like:

```java
      Vertx.clusteredVertx(vertxOptions, result -> {
        System.out.println("VERTX DEBUG: Clustered Vertx Instance Creation Completed.");
        vertx = result.result();
        vertx.exceptionHandler(err -> {
          System.err.println("Erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr ");
          err.printStackTrace();
        });
        vertx.deployVerticle(new SimpleWebServer());
        vertx.deployVerticle(new EventbusConsumer());
        vertx.deployVerticle(new EventbusProducer());
```

**Comment by gokulmss** [comment]
Still we stuck with clusteredVertx time anyone can help us to solve this problem?

**Comment by vietj** [comment]
@gokulmss did you follow @tsegismont advice ?

**Comment by gklsan** [comment]
yeah, I tried that too. After initialize the clusteredVertx vertx object is nil.

**Comment by gokulmss** [comment]
yeah, I tried that too. After initialize the clusteredVertx vertx object is nil.

**Comment by vietj** [comment]
have you checked the asynchronous result ? there must be a failure on it then
