### ISSUE TITLE
vertx.eventbus.handlers explodes when attaching replyhandler

### ISSUE THREAD

**Issue by CountZukula** [vert-x3/vertx-micrometer-metrics#38]
I am trying to send a stream of data through the eventbus which can optionally be caught by a couple of clients. This is a continuation of a previous setup, so I already have a working influx/grafana backend to accommodate the metrics output. I saw some strange behaviour when using the eventbus though: the amount of metrics sent to the backend explodes  when you attach a `replyHandler` to the `send()` method of the eventbus. 

A minimal code example below: running this will steadily increase (for each sent element) the amount of meters in the registry, which eventually hits influx's measurements limit, which results in this output on the console. 

> ... 
3330 [pool-2-thread-1] INFO io.micrometer.influx.InfluxMeterRegistry - successfully sent 10000 metrics to influx
3534 [pool-2-thread-1] INFO io.micrometer.influx.InfluxMeterRegistry - successfully sent 10000 metrics to influx
3844 [pool-2-thread-1] INFO io.micrometer.influx.InfluxMeterRegistry - successfully sent 10000 metrics to influx
3972 [pool-2-thread-1] INFO io.micrometer.influx.InfluxMeterRegistry - successfully sent 10000 metrics to influx
4106 [pool-2-thread-1] INFO io.micrometer.influx.InfluxMeterRegistry - successfully sent 10000 metrics to influx ...

Data in the influx database would look like this:

```
SHOW TAG VALUES FROM "vertx.eventbus.handlers" WITH KEY = "address" limit 100
--
key     | value
address | "1"
address | "10"
address | "100"
address | "1000"
address | "10000"
address | "10001"
```

Removing the reply handler reverts my application to 'normal' behaviour: outputting the metrics I have requested, plus some default ones with the `vertx.` prefix. Is there a way to keep the reply handler working without killing the metrics output?

```
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.micrometer.MicrometerMetricsOptions;
import io.vertx.micrometer.backends.BackendRegistries;

import java.util.concurrent.atomic.AtomicInteger;

public class EventbusHandlerTest {
    public static void main(String[] args) {

        //a minimal micrometermetrics setup
        MicrometerMetricsOptions metricsOptions = new MicrometerMetricsOptions().setEnabled(true);

        //set up the vertx instance that runs the client code
        Vertx vertx = Vertx.vertx(new VertxOptions().setMetricsOptions(metricsOptions));

        //this is the server
        AtomicInteger j = new AtomicInteger();
        vertx.setPeriodic(5L, tid -> {
            for (int i = 0; i < 100; i++) {
                vertx.eventBus().send("somenumber", j.getAndIncrement(),
                        //do not attach this handler and see the amount of meters drop
                        reply -> System.out.println(reply.succeeded())
                );
            }
        });

        //this is the client
        vertx.eventBus().consumer("somenumber", h -> {
            //does not do anything
        });

        //print the amount of meters in the registry
        vertx.setPeriodic(1000L, tid -> {
            System.out.println("#meters = " + BackendRegistries.getDefaultNow().getMeters().size());
        });
    }
}
```

**Comment by jotak** [comment]
Quick solution: you can use a matcher to "redirect" all metrics matching a given pattern to another one:

```
        MicrometerMetricsOptions metricsOptions = new MicrometerMetricsOptions()
          .addLabelMatch(new Match()
            .setDomain(MetricsDomain.EVENT_BUS)
            .setType(MatchType.REGEX)
            .setLabel("address")
            .setValue("^\\d+$")
            .setAlias("reply-address"))
          .setEnabled(true);
```

Since the reply addresses are all like `/^\\d+$/`, this will put them all under label "address: reply-address".

However, this is certainly not an ideal solution. Keep this ticket opened, ideally it should work out of the box.

**Comment by CountZukula** [comment]
Thanks @jotak ! I'll implement your fix in the mean while.

**Comment by jotak** [comment]
Actually, with this upcoming pull request: https://github.com/vert-x3/vertx-micrometer-metrics/pull/35 the `address` label will be disabled by default, so the default case will be safe.

Then it will be up to you to enable & configure it properly or not.

In addition, there's also an opened issue [ https://github.com/eclipse/vert.x/issues/1240 ] that aims to discriminate internal eventbus addresses versus user-defined ones. With that in place, we will be able to put more reliable filters on eventbus addresses.

**Comment by jotak** [comment]
Closing as there was a temporary workaround + a fix for upcoming vert.x 3.6
