### ISSUE TITLE
Filter out internal eventbus addresses

### ISSUE THREAD

**Issue by jotak** [vert-x3/vertx-micrometer-metrics#39]
Once https://github.com/eclipse/vert.x/pull/2516 is merged, internal eventbus addresses will be distinguished with pattern "__vertx.[net|ws|reply].randomUUID".

More generally, we can assume that addresses starting with "__vertx" are internal.
They should be filtered out from eventbus metrics.

Open question: any interest in making this filtering configurable? ie. user will be able to track vertx internal eventbus messages in metrics?

**Comment by tsegismont** [comment]
@jotak I think it's fine to simply ignore them for now (no filtering flag)
