### ISSUE TITLE
Provide HTTP Method key in all the relevant VertxHttpServerMetrics

### ISSUE THREAD

**Issue by mangatmodi** [vert-x3/vertx-micrometer-metrics#41]
For following Metrics, we don't have HTTP Method Key.
  - requests
  - requestResetCount
  - responseTime

It is not possible to have correct analysis without the Method. For e.g. response time for GET and POST on a resource might differ. We are already having HTTP Method available in requestCount, so same can be easily done for others.

**Comment by mangatmodi** [comment]
I have created a PR for the same here https://github.com/vert-x3/vertx-micrometer-metrics/pull/42.

**Comment by tsegismont** [comment]
@jotak make sure to add the milestone on issues fixed in master
