### ISSUE TITLE
Activate Prometheus backend via sysprop

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-micrometer-metrics#45]
It would be nice to be able to activate the Prometheus backend via sysprops.

Also, all JVM metrics.

**Comment by jotak** [comment]
@tsegismont is there some generic converter from sysprops to Vert.x *Options object? That would help, and not only in this module I guess.

**Comment by cescoffier** [comment]
@jotak Yes there is some kind of conversion between system environment and Options. (https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java#L254).

However, it's limited to the Launcher.

**Comment by tsegismont** [comment]
@jotak I am preparing a PR but it will not use what Clément just posted. It will hook in `VertxMetricsFactoryImpl.newOptions()`

**Comment by cescoffier** [comment]
Yes, better avoid it here. We don't want to depend on the launcher.

**Comment by tsegismont** [comment]
@cescoffier well... this method is called only when using the `Laucher` or the Vert.x `bare` command :)

**Comment by tsegismont** [comment]
But the fact is that `BareCommand#configureFromSystemProperties` doesn't help with nested configs. And `VertxMetricsFactoryImpl.newOptions()` was created specifically to let Metrics SPI implementors initialize the options object.

@cescoffier can you confirm it's fine to depend on the Launcher for config via sysprops?

**Comment by tsegismont** [comment]
Closing this one in favor of eclipse-vertx/vert.x#1729

Having an external file (or cli argument) with JSON allows to not only configure the Prometheus backend, but all of this module options and Vert.x core options.
