### ISSUE TITLE
New EB metric to monitor if a consumer cannot cope with messages delivered

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-micrometer-metrics#54]
When a message is delivered locally, a handler task is scheduled for execution. If a consumer cannot keep-up with sent messages, the handler tasks will pile up in the executor queue.

Using the EB metrics SPI, it is possible to determine how many messages have been delivered but not yet handled.

Monitoring such a metrics, users could decided how to adapt to high traffic, e.g. spawning new nodes.

**Comment by sfitts** [comment]
The current SPI would allow you to track the scheduling rate vs. the delivery rate and determine if/when those 2 diverge.  However, something you can't currently do is compute the actual delivery latency.  This is something we find useful for analyzing our application and currently we've had to tack it on above the bus.  It isn't something we leave on all the time, but having the option to gather it would be nice.  It requires carrying timing data in the message headers, but this would be possible to add if the various "xxxMessage" method provided the actual message being processed.

Obviously not a Micrometer issue, but related to the topic at hand.
