### ISSUE TITLE
How to stop collecting Metrics for running application?

### ISSUE THREAD

**Issue by rmohta** [vert-x3/vertx-micrometer-metrics#60]
I have enabled Metrics collection, to be scraped by Prometheus. For any reason, if Prometheus scraper is down for a long period of time - how can I reduce memory pressure on application?

* Can we stop collecting metrics? Looking at [EventBus class close method](https://github.com/vert-x3/vertx-micrometer-metrics/blob/master/src/main/java/io/vertx/micrometer/impl/VertxEventBusMetrics.java#L156) is a no-op.

* Or how to reduce time for which collected metrics are stored? May be related to #27

**Comment by tsegismont** [comment]
Can you elaborate on your issue? Like, what's the difference when metrics
are on/off? How many metrics are you collecting? Which version are you
using? Have you enabled matchers to collect only specific metrics?

Thank you

**Comment by jotak** [comment]
@rmohta more information could help us to better understand the issue.
However, potentially it can be something related to this: https://github.com/vert-x3/vertx-micrometer-metrics/issues/38#issuecomment-400309227
Check this link if the memory pressure is related to the high number of metrics (such as having unbounded eventbus addresses).

Default options in Vert.x 3.6 will be safer in that regard, but it's already something that you can configure.

Also, about stopping the collection of metrics: I haven't tried but you can try this (if you can do it programmatically):
`BackendRegistries.getDefaultNow().close()`
I think it should stop collect metrics.

**Comment by rmohta** [comment]
@jotak using VertX 3.5.3 with worker vertices communicating over event bus. There is no filtering as of now (will look into this). 
My app generates about 4MB+ metrics output for every scrape, with many related to EventBus for every address.

**Comment by rmohta** [comment]
We have following meterFilter
```
               return DistributionStatisticConfig.builder()
                    .percentilesHistogram(true)
                    .build()
                    .merge(config);
```

**Comment by jotak** [comment]
So, as mentioned in the link above, if you don't need that level of granularity on eventbus metrics (that is, you don't need to store eventbus metrics per address) you can do the following on Vert.x options:

```
  new MicrometerMetricsOptions()
    // ...
    .addLabelMatch(new Match()
      // Set all values for "address" label to "_", for all domains. In other words, it's like disabling the "address" label.
      .setLabel("address")
      .setType(MatchType.REGEX)
      .setValue(".*")
      .setAlias("_"))
  // ...
```
You won't need to do it in the upcoming vert.x 3.6
