### ISSUE TITLE
Upgrade Micrometer to 1.1.0 

### ISSUE THREAD

**Issue by bckfnn** [vert-x3/vertx-micrometer-metrics#61]
How about an upgrade to micrometer 1.1.0 before vert.x 3.6.0 is finalized?

**Comment by vietj** [comment]
@jotak ?

**Comment by jotak** [comment]
Ok, investigating changes...

**Comment by jotak** [comment]
Hmm, looks like something changed with the influx naming convention, I've always thought default convention was to use dot separators for influx but in micrometers source code comment it states telegraf convention is to use underscores.
I guess we'll stick to micrometer default and use underscores as well.

**Comment by tsegismont** [comment]
@jotak Is this configurable? I believe it's fine to use the new default, as long as we document this in the [3.6 breaking changes page](https://github.com/vert-x3/wiki/wiki/3.6.0-Breaking-Changes)

**Comment by bckfnn** [comment]
I think the use of dots in influx names in micrometer v1.0.5 was a regression that only occurred in that version:

https://github.com/micrometer-metrics/micrometer/issues/693

**Comment by jotak** [comment]
@tsegismont this is configurable indirectly via micrometer registry accessor. Does breaking changes need to be documented for TP stuff?

@bckfnn yes I've seen this issue, so I understand this is an intended change and not a bug. I couldn't find a clear statement that snakecase is a convention for influx however.

**Comment by tsegismont** [comment]
@jotak what do you mean with _TP_?

**Comment by jotak** [comment]
@bckfnn you're right, the last micrometer update that we did was to 1.0.5, and we fixed the names for influx registry in our tests: https://github.com/vert-x3/vertx-micrometer-metrics/pull/37 . I thought at the moment it was an intended behaviour, but turning out it was a bug.

**Comment by jotak** [comment]
Actually, there's no breaking change @tsegismont . The use of dots was introduced only in a previous commit on master and never backported in 3.5
