### ISSUE TITLE
Micrometer 1.1 improvements to investigate

### ISSUE THREAD

**Issue by jotak** [vert-x3/vertx-micrometer-metrics#62]
Investigate some of the improvements from mm 1.1 that don't come out of the box (meaning, we need to implement something)

See https://github.com/micrometer-metrics/micrometer/releases/tag/v1.1.0

Ex:
- [ ] Adding config flag / helper to enable DiskSpace metrics?
- <strike>  Use strong reference on Gauges (should help simplify our code) </strike> it actually doesn't help ; our concurrent hashmap is still needed because of how it's implemented in micrometer as something kinda stateless
- [ ] Inject vert.x HTTP client for push-based registries (such as influx)

**Comment by tsegismont** [comment]
Outdated
