### ISSUE TITLE
Setup performance tests

### ISSUE THREAD

**Issue by jotak** [vert-x3/vertx-micrometer-metrics#63]
We should have some perf tests on high volume of metrics to track improvements and regressions on code changes and/or micrometer updates.

**Comment by vietj** [comment]
couple of points:

- can we come up with a plan for that ?
   - scenarii we want to test each component separately (HttpServer, HttpClient, etc...)
   - with a backend or no backend ?
   - enabled / disabled to compare overhead
- we do have a performance lab for testing this

**Comment by rmohta** [comment]
@vietj @jotak : Is this still an open issue? 
If yes, is there a separate performance lab provisioned for this?

**Comment by vietj** [comment]
@rmohta we do have an internal lab (behind VPN) for this, so I think testing plan would be in community and anyone can run tests and we could run them in the private performance lab

yes it remains an open issue

**Comment by rmohta** [comment]
Sounds good @vietj. If this is still an open issue, I can start documenting some test plans and share them here. Do we have any particular preference for performance test like any particular software or I am open to choose one? And I am assuming this ticket is **not** for micro-benchmarks using jmh.

**Comment by tsegismont** [comment]
Outdated
