### ISSUE TITLE
Label.HTTP_CODE is not exposed in the exposed request related histograms  

### ISSUE THREAD

**Issue by u6f6o** [vert-x3/vertx-micrometer-metrics#68]
According to the [documentation](https://vertx.io/docs/vertx-micrometer-metrics/java/#_labels_and_matchers), one can enrich the exposed metrics by useful labels like HTTP_PATH, HTTP_METHOD and so on. 

One label I am particularly interested in, is the HTTP_CODE label. I activated this label in my setup method like the following: 

```
fun create(meterRegistry: MeterRegistry): VertxOptions {
    return VertxOptions()
        .setMetricsOptions(
            MicrometerMetricsOptions()
                .setEnabled(true)
                .setMicrometerRegistry(meterRegistry)
                .setPrometheusOptions(VertxPrometheusOptions().setEnabled(true))
                .setLabels(EnumSet.of(Label.HTTP_PATH, Label.HTTP_METHOD, Label.HTTP_CODE)))
}
```
When I query the metrics endpoint, I see that this label is exposed with the standard request count metrics: 
```
curl http://127.0.0.1:8080/internal/prometheus | grep -i http_server | grep code
vertx_http_server_requestCount_total{code="200",method="GET",path="/internal/prometheus",} 1.0
```
The problem is that this label is not included in the exposed histogram metrics though: 

```
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="5.0E-9",} 0.0
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="1.0E-8",} 0.0
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="2.5E-8",} 0.0
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="5.0E-8",} 0.0
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="1.0E-7",} 0.0
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="2.5E-7",} 0.0
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="5.0E-7",} 0.0
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="1.0E-6",} 0.0
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="2.5E-6",} 0.0
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="5.0E-6",} 0.0
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="1.0E-5",} 0.0
vertx_http_server_responseTime_seconds_bucket{method="GET",path="/internal/prometheus",le="+Inf",} 0.0
```

**Comment by jotak** [comment]
This is as described in the documentation, this metric is currently not labelled with the response code: https://vertx.io/docs/vertx-micrometer-metrics/java/#_vert_x_core_tools_metrics

Each metric may have its own set of labels for various reasons.
However in that case it seems reasonable to add a response code label, indeed. I'll look into it.

**Comment by u6f6o** [comment]
Thank you @jotak 

To give a little bit of background: I am migrating one of our services from clojure to kotlin and vertx. A main part of this task is to see how well vertx fits in our current setup which is mostly dominated by spring boot and clojure atm. 

If I could be of any help by providing a pull-request, please let me know

**Comment by jotak** [comment]
@u6f6o I did a PR, feel free to test it: #70 for next vertx version (3.7)

**Comment by u6f6o** [comment]
@jotak I just gave it a try and it worked both for server and client metrics 👍
