### ISSUE TITLE
Using custom Prometheus collector registry

### ISSUE THREAD

**Issue by nolequen** [vert-x3/vertx-micrometer-metrics#71]
In my application I have own Prometheus metrics and I want to use the same collector registry as for Vert.x metrics.

**Comment by jotak** [comment]
Hi @nolequen 
I think you can already do that with `MicrometerMetricsOptions.setMicrometerRegistry`.
Looking at your commit, what you want to do is to re-use not the _micrometer_ registry, but the _collector registry_ from Prometheus client (without micrometer).

I guess you could do something like this, while setting up your vert.x options:

```java
    PrometheusMeterRegistry micrometerRegistry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT, myCollectorRegistry, Clock.SYSTEM);
    metricsOptions.setMicrometerRegistry(micrometerRegistry);
```

without any change in vertx code. Does it sound good?

**Comment by nolequen** [comment]
hi @jotak 
Your solution looks nice, but unfortunately it ignores specified VertxPrometheusOptions.

**Comment by jotak** [comment]
@nolequen that's right ... so you would have to basically duplicate this code within your application code: https://github.com/vert-x3/vertx-micrometer-metrics/blob/master/src/main/java/io/vertx/micrometer/backends/PrometheusBackendRegistry.java

I'm going to patch so don't you don't have to.

**Comment by nolequen** [comment]
@jotak why you want to patch by yourself? why not to merge the PR?

**Comment by jotak** [comment]
@nolequen since there's already a mechanism to provide a registry, I'm not sure that adding a second one is really necessary. It just has to be fixed regarding the issue you raised (and this, regardless if your PR is merged or not). In terms of API, having different ways to achieve the same goal may be confusing.

**Comment by nolequen** [comment]
@jotak ok. I'll be waiting for the fix. thanks!
