### ISSUE TITLE
NullPointerException in io.vertx.micrometer.impl.VertxEventBusMetrics.handlerUnregistered

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-micrometer-metrics#74]
We are seeing an intermittent, but frequent (at load it happened about 300K times over a 30 minute span), NPE in `io.vertx.micrometer.impl.VertxEventBusMetrics.handlerUnregistered`.  Here is the stack starting from where our code is calling `unregister` on an event bus consumer.

```
22:53:20.246 [vert.x-eventloop-thread-1] ERROR i.v.c.e.impl.HandlerRegistration - Failed to handleMessage. address: vantiq-local://1dfd5251-50e3-11e9-b428-02421950845d
java.lang.NullPointerException: null
        at io.vertx.micrometer.impl.VertxEventBusMetrics.handlerUnregistered(VertxEventBusMetrics.java:79)
        at io.vertx.micrometer.impl.VertxEventBusMetrics.handlerUnregistered(VertxEventBusMetrics.java:33)
        at io.vertx.core.eventbus.impl.HandlerHolder.setRemoved(HandlerHolder.java:48)
        at io.vertx.core.eventbus.impl.EventBusImpl.removeLocalRegistration(EventBusImpl.java:307)
        at io.vertx.core.eventbus.impl.EventBusImpl.removeRegistration(EventBusImpl.java:289)
        at io.vertx.core.eventbus.impl.HandlerRegistration.doUnregister(HandlerRegistration.java:176)
        at io.vertx.core.eventbus.impl.HandlerRegistration.unregister(HandlerRegistration.java:135)
        at io.vertx.core.eventbus.impl.VantiqMessageProducerImpl.close(VantiqMessageProducerImpl.java:235)
```

I've been over the code a bunch and I honestly don't see how this is possible.  I don't see where/when the "metrics" property of HandlerRegistration would get cleared and even if there were concurrent calls to unregister (which I don't believe there are) there is a synchronized block in `io.vertx.core.eventbus.impl.HandlerHolder.setRemoved` that should prevent the metrics unregister from happening more than once.  And yet... this is very consistent behavior.

I've also been unable to reproduce this outside of our full server running under heavy load, so I don't have anything to reproduce the issue.  About all I can do on our end is disable metric collection in Vert.x (which I'd obviously prefer not to do).  In the code about all I could recommend is a check for `null` in the impacted routine so that at least we can avoid the NPE.

**Comment by jotak** [comment]
We could probably do a defensive null-check in `VertxEventBusMetrics.handlerUnregistered` , but still there must be something going wrong in `HandlerRegistration` class.

@vietj , any idea? It's like the `VertxEventBusMetrics.handlerUnregistered` method being called without any prior call to `VertxEventBusMetrics.handlerRegistered`.

**Comment by vietj** [comment]
it might be a bug (race?), if you have a reproducer I can investigate.

**Comment by sfitts** [comment]
@vietj unfortunately I haven't been able to reproduce this outside of live fire/high load situations.  So I have no idea where to even start to boil it down to something simple and Vert.x only.

@jotak interesting thought -- I hadn't considered a possible race between the registration and unregistration code.  Given that we have a registered consumer in our hands I was more focused on possible duplicate calls to unregister.  But maybe there is some deferred/async initialization that doesn't have time to complete if you call unregister fast enough.  Back into the code ;).

**Comment by sfitts** [comment]
@vietj 

I think I know what is happening here.  The registration in question is global and we are running in a clustered environment.  So I think we are creating the consumer and then calling `unregister` on it *before* it has had a chance to fully propagate the subscription across the cluster.  As a result `HandlerRegistration.setResult` method will not have been called and the `metrics` filed wont' be set.  This then results in the NPE during unregister.

I have no idea is this is supposed to be legal, but even if it isn't it would seem that rejecting the premature unregister would be better than violating what appears to be an invariant in the metrics SPI contract.

I'm going to relog this in the core repo.

**Comment by vietj** [comment]
thanks Sean.

**Comment by vietj** [comment]
should be fixed by https://github.com/eclipse-vertx/vert.x/pull/2901
