### ISSUE TITLE
java.lang.NoClassDefFoundError: io/micrometer/prometheus/PrometheusMeterRegistry

### ISSUE THREAD

**Issue by hc-codersatlas** [vert-x3/vertx-micrometer-metrics#79]
Hi, getting java.lang.NoClassDefFoundError: io/micrometer/prometheus/PrometheusMeterRegistry

Because it's required in BackendRegistries.

I'm not using Prometheus  and so haven't imported it in micrometer. Specifying a custom meterRegistry as per documentation.

**Comment by manzur** [comment]
Hey, 

I had a similar issue, so made a band aid fix. As mentioned in the commit message, branching can be re-written in a different way, as the option with specifying both registry and additional options seems to be not mentioned in the docs.

**Comment by jotak** [comment]
Thank you @hc-codersatlas , @manzur for spotting the issue. @manzur I'm reviewing your PR.
