### ISSUE TITLE
About Enable PublishQuantiles.

### ISSUE THREAD

**Issue by lemon-li** [vert-x3/vertx-micrometer-metrics#83]
Hello.
If I set `PublishQuantiles = true`, there are more than 200 items vertx_http_client_responseTime_seconds_bucket per scrap,
Is there any way to reduce it?

**Comment by jotak** [comment]
Hi @lemon-li ,

This module uses Micrometer metrics under the hood, and when you set `publishQuantiles(true)` it just activates the corresponding flag within micrometer, which is named `publishPercentileHistogram` and is described here: https://micrometer.io/docs/concepts#_histograms_and_percentiles

Another way to get quantiles is to explicitly require specific buckets to be available. It's described in vert.x documentation:
https://vertx.io/docs/vertx-micrometer-metrics/java/#_advanced_usage

```java
PrometheusMeterRegistry registry = (PrometheusMeterRegistry) BackendRegistries.getDefaultNow();
registry.config().meterFilter(
    new MeterFilter() {
      @Override
      public DistributionStatisticConfig configure(Meter.Id id, DistributionStatisticConfig config) {
        return DistributionStatisticConfig.builder()
            .percentiles(0.95, 0.99)
            .build()
            .merge(config);
      }
    });
```

So you will drastically reduce the number of exposed metrics, but this approach has a serious drawback when querying metrics: the resulted values will not be aggregable across dimensions.

Note that you can access the underlying micrometer configuration if you want to try other setups. I can see in micrometer doc that there are some fields to control number of buckets : `minimumExpectedValue` and `maximumExpectedValue`. I haven't played with, personally, but if you want to give a try then we would appreciate some feedback, maybe it's something we could have directly configurable in vertx metrics config.

**Comment by lemon-li** [comment]
Thank you very much for your reply, I hope to add configuration to vertx metrics config.
I tried to change `maximumExpectedValue,`  it work.
