### ISSUE TITLE
Exception when jvm metrics are enabled

### ISSUE THREAD

**Issue by tjakopan** [vert-x3/vertx-micrometer-metrics#84]
If jvm metrics are enabled getting the metrics snapshot will fail.

The cause of the error is line 99 in io.vertx.micrometer.impl.MetricsServiceImpl which is trying to cast CumulativeFunctionCounter to Counter.
The following exception is caught in line 126 in RoutingContextImplBase - java.lang.ClassCastException: io.micrometer.core.instrument.cumulative.CumulativeFunctionCounter cannot be cast to io.micrometer.core.instrument.Counter.

I've created the project which can reproduce the issue - https://github.com/tjakopan/micrometer-jvm-metrics-error-reproducer

**Comment by tjakopan** [comment]
Reproducer is for vert.x 3.8.0, but I've experienced this in 3.7.0.

**Comment by jotak** [comment]
@tjakopan thanks for the report, I'm starting to look at it

**Comment by tjakopan** [comment]
No problem. This might be the fix, although I still need to test it. I've done it on 3.7.1 tag since my project was on 3.7.0, but 3.7.1 contains another fix for Prometheus registry (instanceof).

`  private static JsonObject metricToJson(Meter meter) {
    JsonObject tags = new JsonObject();
    meter.getId().getTags().forEach(tag -> tags.put(tag.getKey(), tag.getValue()));
    JsonObject obj = new JsonObject().put("tags", tags);
    meter.use(gauge -> gaugeToJson(obj, gauge),
      counter -> counterToJson(obj, counter),
      timer -> timerToJson(obj, timer),
      summary -> summaryToJson(obj, summary),
      longTaskTimer -> longTaskTimerToJson(obj, longTaskTimer),
      timeGauge -> timeGaugeToJson(obj, timeGauge),
      functionCounter -> functionCounterToJson(obj, functionCounter),
      functionTimer -> functionTimerToJson(obj, functionTimer),
      m -> obj.put("type", "unknown"));
    return obj;
  }

  private static JsonObject longTaskTimerToJson(JsonObject obj, LongTaskTimer longTaskTimer) {
    return obj.put("type", "longTaskTimer")
      .put("activeTasks", longTaskTimer.activeTasks())
      .put("durationMs", longTaskTimer.duration(TimeUnit.MILLISECONDS));
  }

  private static JsonObject timeGaugeToJson(JsonObject obj, TimeGauge timeGauge) {
    return obj.put("type", "timeGauge")
      .put("valueMs", timeGauge.value(TimeUnit.MILLISECONDS));
  }

  private static JsonObject functionCounterToJson(JsonObject obj, FunctionCounter functionCounter) {
    return obj.put("type", "functionCounter")
      .put("count", functionCounter.count());
  }

  private static JsonObject functionTimerToJson(JsonObject obj, FunctionTimer functionTimer) {
    return obj.put("type", "functionTimer")
      .put("count", functionTimer.count())
      .put("totalTimeMs", functionTimer.totalTime(TimeUnit.MILLISECONDS))
      .put("meanMs", functionTimer.mean(TimeUnit.MILLISECONDS));
  }
`

**Comment by jotak** [comment]
Yes, that sounds to be the right way to do. Are you going to open a PR?

**Comment by tjakopan** [comment]
I can do, although I haven't done it for vert.x yet, so might need some guidance.

Can it be done on 3.7.1? Will there be 3.7.2? Or should I do it on 4.0.0?

**Comment by jotak** [comment]
You can do it on master (so it's 4.0.0) and I'll cherry-pick to the other relevant branches when it's merged. Or the other way around if you prefer.

There's no much ceremony, if you can write a small test it's even better. There's already a couple of those in MetricsServiceImplTest.

**Comment by tjakopan** [comment]
Will do that then. I'll write a test, but it'll have to be in the next couple of days and then I'll open the PR.

**Comment by tjakopan** [comment]
Hi, I've opened the PR - #85

**Comment by jotak** [comment]
it's merged & cherry-picked to 3.8 branch.
Thanks for your contrib!

**Comment by HaidStefan** [comment]
Hello, I currently have the same issue but it is still not working for me.

The vertx-version I use is 3.7.0 with the rxjava extension and I use the following micrometer dependencies:
```
<dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-micrometer-metrics</artifactId>
    <version>3.9.2</version>
</dependency>
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-registry-prometheus</artifactId>
    <version>1.1.0</version>
</dependency>
```

The code I'm using to get the Metrics Snapshot:
```
if (vertx.isMetricsEnabled()) {
	MetricsService metricsService = MetricsService.create(vertx);
	JsonObject metricsSnapshot = metricsService.getMetricsSnapshot();
	LOGGER.info("metrics: {}", metricsSnapshot);
}
```
If the JvmMetrics are enabled i receive the same Error as above:
```
java.lang.ClassCastException: io.micrometer.core.instrument.cumulative.CumulativeFunctionCounter cannot be cast to io.micrometer.core.instrument.Counter
	at io.vertx.micrometer.impl.MetricsServiceImpl.metricToJson(MetricsServiceImpl.java:99)
	at java.util.stream.Collectors.lambda$mapping$8(Collectors.java:355)
	at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:909)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.vertx.micrometer.impl.MetricsServiceImpl.snapshot(MetricsServiceImpl.java:86)
	at io.vertx.micrometer.impl.MetricsServiceImpl.getMetricsSnapshot(MetricsServiceImpl.java:51)
	at io.vertx.rxjava.micrometer.MetricsService.getMetricsSnapshot(MetricsService.java:99)
```

Shouldn't this have been fixed from the 3.8.1 Version? I've also tried to use 3.7.1, 3.7.5 and the 4.0.1 Version and all had the same Exception.

**Comment by tjakopan** [comment]
It is fixed, it's not throwing that exception for us on higher versions of vertx.

Double check that maven is actually resolving metrics as v3.9.2 and not v3.7.0.

**Comment by HaidStefan** [comment]
Ohh my bad. So Vertx Version 3.8.1 + is required too in this case.
