### ISSUE TITLE
Missing queue-delay for http client metrics

### ISSUE THREAD

**Issue by sudheerbhat** [vert-x3/vertx-micrometer-metrics#88]
The current VertxHttpClientMetrics is missing the queue delay timer for the http client. This is useful metric IMHO as it could help in tuning the http client pool size.

**Comment by jotak** [comment]
@vietj that would be a timer between `enqueueRequest` and `dequeueRequest` I guess : https://github.com/vert-x3/vertx-micrometer-metrics/blob/master/src/main/java/io/vertx/micrometer/impl/VertxHttpClientMetrics.java#L71-L78

Is it guaranteed that all enqueued requests are dequeued or are there other paths (such as cancellation or whatever) ?

**Comment by sfitts** [comment]
Looking at the SPI you definitely have the context you need to do this (the object created by `createEndpoint` is tracked through the other calls.  There doesn't appear to be anyway else out of the queue, so it could be the timer you suggest.

If not a timer, then at least a gauge so you can visualize the queue depths and make sure your pool sizes are correct.

**Comment by vietj** [comment]
@jotak I think some requests might not be dequeued when the client is closed but for sure we would need to check that with a test in vertx core

I think indeed it would be great to add such feature.

**Comment by vietj** [comment]
by test I mean:

1. create an http client request
2. the server does not send a response
3. the client is closed
4. check what happens

**Comment by vietj** [comment]
also check what are the other path of failures, because if the client is closed then the corresponding HttpClientMetrics will be closed as well.
