### ISSUE TITLE
Custom Tag Provider

### ISSUE THREAD

**Issue by dtaveras** [vert-x3/vertx-micrometer-metrics#89]
The generation of tags is tied to Label types. Is there a way to add a custom tag?
I do understand that there is common tags in the MeterRegistry but i was more looking for one when creating the Meter. As an example I want to tag each meter with a user

**Comment by jotak** [comment]
Hi @dtaveras ,

As you say, the MeterRegistry has common tags ; and you can get that registry to impact all registered metrics. E.g.

```java
    MeterRegistry registry = BackendRegistries.getDefaultNow();
    registry.config().commonTags("user", "alice");
```
Is that not what you're looking for?

**Comment by dtaveras** [comment]
I was more interested in being able to extract more information based on the request, so having a tag provider with signature Request -> [Tag]. 
As example we also use https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-jersey2/src/main/java/io/micrometer/jersey2/server/MetricsRequestEventListener.java which accepts a tag provider with the signature above.

**Comment by dtaveras** [comment]
common tags will do for now, was just curious if i missed something.

**Comment by jotak** [comment]
I think I get it, it seems like a good enhancement to add.

**Comment by dtaveras** [comment]
Thanks, great job with this library. A ton of great features and easy to configure.

**Comment by vietj** [comment]
@jotak do we have a contributor for this enhancement ?

**Comment by jotak** [comment]
@vietj not that I know. I'm going to take a look.
