### ISSUE TITLE
Label matches don't seem to actually filter anything.

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-micrometer-metrics#92]
Adding a label match would seem to imply that if a given meter has a non-matching value for the given label, it should be rejected.  However, the current implementation is using these to create Micrometer "accept" filters.  All those can do is guarantee acceptance.  This means that for non-matching meters the response is "NEUTRAL" which by default means the meter will be added.

At a minimum it seems that there needs to be a way to specify that a given label match should be used to create a "deny" filter instead (thus allowing for a non-match to be "denied").

**Comment by jotak** [comment]
Oh, that's right! We need to reverse the logic
https://micrometer.io/docs/concepts#_denyaccept_meters

**Comment by jotak** [comment]
For anybody who'd like a workaround before the fix is merged, it's possible to achieve the same directly via micrometer registry config:

```java
    MeterRegistry registry = BackendRegistries.getDefaultNow();
    registry.config().meterFilter(
      MeterFilter.deny(id -> {
        String tagValue = id.getTag("label-name");
        return !"label-value".equals(tagValue);
      }));
```
