### ISSUE TITLE
MicrometerMetricsOptions does not override setFactory

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-micrometer-metrics#96]
### Version

3.8.5

### Context

The class `MicrometerMetricsOptions` does not override `setFactory` from the parent class, so it can't be used fluently if that method is called.  (FWIW, it does override `setEnabled`).

### Steps to reproduce

Try doing the following:

```
new MicrometerMetricsOptions()
                    .setFactory(null)
                    .setEnabled(true)
                    .setRegistryName("name");
```

It won't compile.  If you remove the `setFactory` method, it will.

### Workaround

Put the call to `setFactory` last.  This results in the type being `MetricsOptions`, but much of the time that's sufficient (or you can just cast it to what you know it is, but of course that's a bit ugly).

**Comment by jotak** [comment]
I'm looking into it
